---
- name: Upgrade os packages
  hosts: all
  vars:
    ansible_python_interpreter: auto

  tasks:
  - name: Install yum-utils for needs-restarting functionality (RHEL-based distributions)
    package:
      name:  yum-utils
      state: latest
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Upgrade all packages
    package:
      name: '*'
      state: latest

  - name: Set reboot_server to default to false
    set_fact:
      reboot_server: False
    when: reboot_only_if_needed is undefined

  - name: Host Reboot | Detect if reboot is required
    command: needs-restarting --reboothint
    register: needs_restart_result
    failed_when: needs_restart_result.rc > 1
    changed_when: needs_restart_result.rc == 1
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Set reboot_server if needs_restart_result == 1
    set_fact:
      reboot_server: True
    when: ansible_facts['os_family'] == 'RedHat' and needs_restart_result.rc == 1

  - name: Check if reboot is required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file
    when: ansible_facts['os_family'] == 'Debian'

  - name: Set reboot_server if reboot_required_file exists
    set_fact:
      reboot_server: True
    when: ansible_facts['os_family'] == 'Debian' and reboot_required_file.stat.exists

  - name: Check value of needs_restart_result
    debug:
        msg: "{{reboot_server}}"

  - name: Reboot the machine with all defaults options
    reboot:
    when: reboot_server == True
